FROM nvidia/cuda:12.0.0-runtime-ubuntu22.04

WORKDIR /Desktop/AVDC_GDP_Cranfield_2023

COPY . .

ADD https://ultralytics.com/assets/Arial.ttf /root/.config/Ultralytics/

RUN apt-get update \
    && apt-get install --no-install-recommends -y  \
        libgl1-mesa-glx libglib2.0-0 python3 python3-pip \
        gcc python3-dev \
    && pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116 \
    && pip3 install ultralytics \
    && rm -rf /var/lib/apt/lists/*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIV

